"""Add scenario versioning tables - base_scenarios, scenario_patches, versioned_scenarios

Revision ID: 0ba3dffefb22
Revises: d9529894d0f8
Create Date: 2025-09-09 19:41:22.548096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba3dffefb22'
down_revision: Union[str, None] = 'd9529894d0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_base_scenarios_base_id', 'base_scenarios', ['base_id'], unique=False)
    op.create_index('idx_base_scenarios_created', 'base_scenarios', ['created_at'], unique=False)
    op.create_index('idx_base_scenarios_name', 'base_scenarios', ['name'], unique=False)
    op.create_index(op.f('ix_base_scenarios_base_id'), 'base_scenarios', ['base_id'], unique=True)
    op.create_index(op.f('ix_base_scenarios_id'), 'base_scenarios', ['id'], unique=False)
    op.create_table('scenario_patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.String(length=255), nullable=False),
    sa.Column('base_scenario_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('removed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_scenario_id'], ['base_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patches_base_version', 'scenario_patches', ['base_scenario_id', 'version'], unique=False)
    op.create_index('idx_patches_created', 'scenario_patches', ['created_at'], unique=False)
    op.create_index('idx_patches_patch_id', 'scenario_patches', ['patch_id'], unique=False)
    op.create_index(op.f('ix_scenario_patches_base_scenario_id'), 'scenario_patches', ['base_scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_patches_id'), 'scenario_patches', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_patches_patch_id'), 'scenario_patches', ['patch_id'], unique=True)
    op.create_table('versioned_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_scenario_id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_scenario_id'], ['base_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patch_id'], ['scenario_patches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_versioned_scenarios_base_patch', 'versioned_scenarios', ['base_scenario_id', 'patch_id'], unique=False)
    op.create_index('idx_versioned_scenarios_name', 'versioned_scenarios', ['name'], unique=False)
    op.create_index('idx_versioned_scenarios_scenario_id', 'versioned_scenarios', ['scenario_id'], unique=False)
    op.create_index('idx_versioned_scenarios_user_created', 'versioned_scenarios', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_versioned_scenarios_base_scenario_id'), 'versioned_scenarios', ['base_scenario_id'], unique=False)
    op.create_index(op.f('ix_versioned_scenarios_id'), 'versioned_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_versioned_scenarios_patch_id'), 'versioned_scenarios', ['patch_id'], unique=False)
    op.create_index(op.f('ix_versioned_scenarios_scenario_id'), 'versioned_scenarios', ['scenario_id'], unique=True)
    op.create_index(op.f('ix_versioned_scenarios_user_id'), 'versioned_scenarios', ['user_id'], unique=False)
    # First, update the runs table to use versioned_scenarios
    op.add_column('runs', sa.Column('versioned_scenario_id', sa.Integer(), nullable=True))
    op.drop_index('ix_runs_scenario_id', table_name='runs')
    op.drop_index('idx_runs_scenario_status', table_name='runs')
    op.drop_constraint('runs_scenario_id_fkey', 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'versioned_scenarios', ['versioned_scenario_id'], ['id'], ondelete='CASCADE')
    op.drop_column('runs', 'scenario_id')
    op.create_index('idx_runs_scenario_status', 'runs', ['versioned_scenario_id', 'status'], unique=False)
    op.create_index(op.f('ix_runs_versioned_scenario_id'), 'runs', ['versioned_scenario_id'], unique=False)
    
    # Now we can safely drop the scenarios table
    op.drop_index('idx_scenarios_name', table_name='scenarios')
    op.drop_index('idx_scenarios_user_created', table_name='scenarios')
    op.drop_index('ix_scenarios_id', table_name='scenarios')
    op.drop_index('ix_scenarios_user_id', table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key('runs_scenario_id_fkey', 'runs', 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_runs_versioned_scenario_id'), table_name='runs')
    op.drop_index('idx_runs_scenario_status', table_name='runs')
    op.create_index('idx_runs_scenario_status', 'runs', ['scenario_id', 'status'], unique=False)
    op.create_index('ix_runs_scenario_id', 'runs', ['scenario_id'], unique=False)
    op.drop_column('runs', 'versioned_scenario_id')
    op.create_table('scenarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scenario_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='scenarios_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scenarios_pkey')
    )
    op.create_index('ix_scenarios_user_id', 'scenarios', ['user_id'], unique=False)
    op.create_index('ix_scenarios_id', 'scenarios', ['id'], unique=False)
    op.create_index('idx_scenarios_user_created', 'scenarios', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_scenarios_name', 'scenarios', ['name'], unique=False)
    op.drop_index(op.f('ix_versioned_scenarios_user_id'), table_name='versioned_scenarios')
    op.drop_index(op.f('ix_versioned_scenarios_scenario_id'), table_name='versioned_scenarios')
    op.drop_index(op.f('ix_versioned_scenarios_patch_id'), table_name='versioned_scenarios')
    op.drop_index(op.f('ix_versioned_scenarios_id'), table_name='versioned_scenarios')
    op.drop_index(op.f('ix_versioned_scenarios_base_scenario_id'), table_name='versioned_scenarios')
    op.drop_index('idx_versioned_scenarios_user_created', table_name='versioned_scenarios')
    op.drop_index('idx_versioned_scenarios_scenario_id', table_name='versioned_scenarios')
    op.drop_index('idx_versioned_scenarios_name', table_name='versioned_scenarios')
    op.drop_index('idx_versioned_scenarios_base_patch', table_name='versioned_scenarios')
    op.drop_table('versioned_scenarios')
    op.drop_index(op.f('ix_scenario_patches_patch_id'), table_name='scenario_patches')
    op.drop_index(op.f('ix_scenario_patches_id'), table_name='scenario_patches')
    op.drop_index(op.f('ix_scenario_patches_base_scenario_id'), table_name='scenario_patches')
    op.drop_index('idx_patches_patch_id', table_name='scenario_patches')
    op.drop_index('idx_patches_created', table_name='scenario_patches')
    op.drop_index('idx_patches_base_version', table_name='scenario_patches')
    op.drop_table('scenario_patches')
    op.drop_index(op.f('ix_base_scenarios_id'), table_name='base_scenarios')
    op.drop_index(op.f('ix_base_scenarios_base_id'), table_name='base_scenarios')
    op.drop_index('idx_base_scenarios_name', table_name='base_scenarios')
    op.drop_index('idx_base_scenarios_created', table_name='base_scenarios')
    op.drop_index('idx_base_scenarios_base_id', table_name='base_scenarios')
    op.drop_table('base_scenarios')
    # ### end Alembic commands ###
