"""Data models for retirement planning scenarios."""

from .account_evolution import (
    AccountBalance,
    AccountEvolution,
    AccountEvolutionEngine,
    Transaction,
    calculate_portfolio_return,
    create_account_evolution_engine_from_scenario,
    create_account_evolution_from_scenario_account,
    validate_account_balance_consistency,
)
from .baseline_expenses import (
    ExpenseCategory,
    ExpenseEngine,
    HealthcareExpenseCategory,
    HousingExpenseCategory,
    LumpyEvent,
    TransportationExpenseCategory,
    calculate_expense_inflation_impact,
    create_expense_engine_from_scenario,
    validate_expense_timing,
)
from .income_engine import (
    BusinessIncome,
    EmploymentIncome,
    IncomeCategory,
    IncomeChangeEvent,
    IncomeEngine,
    InvestmentIncome,
    RentalIncome,
    RetirementIncome,
    SelfEmploymentIncome,
    VariableIncome,
    calculate_income_present_value,
    create_income_engine_from_scenario,
    validate_income_timing,
)
from .mortgage_amortization import (
    AmortizationSchedule,
    MortgageCalculator,
    PaymentBreakdown,
    RefinancingScenario,
    create_sample_mortgage,
    create_sample_refinancing,
)
from .scenario import (
    Accounts,
    Expenses,
    Household,
    Incomes,
    Liabilities,
    MarketModel,
    Policies,
    Scenario,
    ScenarioMetadata,
    Strategy,
)
from .social_security import (
    SocialSecurityBenefit,
    SocialSecurityEngine,
    calculate_social_security_present_value,
    create_social_security_engine_from_scenario,
    validate_social_security_timing,
)

__all__ = [
    "Scenario",
    "Household",
    "Accounts",
    "Liabilities",
    "Incomes",
    "Expenses",
    "Policies",
    "MarketModel",
    "Strategy",
    "ScenarioMetadata",
    "AmortizationSchedule",
    "MortgageCalculator",
    "PaymentBreakdown",
    "RefinancingScenario",
    "create_sample_mortgage",
    "create_sample_refinancing",
    "ExpenseCategory",
    "HousingExpenseCategory",
    "TransportationExpenseCategory",
    "HealthcareExpenseCategory",
    "LumpyEvent",
    "ExpenseEngine",
    "create_expense_engine_from_scenario",
    "calculate_expense_inflation_impact",
    "validate_expense_timing",
    "Transaction",
    "AccountBalance",
    "AccountEvolution",
    "AccountEvolutionEngine",
    "create_account_evolution_from_scenario_account",
    "create_account_evolution_engine_from_scenario",
    "calculate_portfolio_return",
    "validate_account_balance_consistency",
    "SocialSecurityBenefit",
    "SocialSecurityEngine",
    "create_social_security_engine_from_scenario",
    "validate_social_security_timing",
    "calculate_social_security_present_value",
    "IncomeCategory",
    "EmploymentIncome",
    "SelfEmploymentIncome",
    "BusinessIncome",
    "InvestmentIncome",
    "RentalIncome",
    "RetirementIncome",
    "VariableIncome",
    "IncomeChangeEvent",
    "IncomeEngine",
    "create_income_engine_from_scenario",
    "validate_income_timing",
    "calculate_income_present_value",
]

# Historical data imports

# Update __all__ list
__all__.extend(
    [
        "AssetClass",
        "CSVSource",
        "DataSourceConfig",
        "FREDSource",
        "HistoricalDataManager",
        "HistoricalDataPoint",
        "HistoricalDataSet",
        "YahooFinanceSource",
        "create_default_asset_classes",
        "create_default_data_sources",
        "HistoricalReturnsProvider",
        "create_historical_returns_provider",
    ]
)
